### ISSUE TITLE
Windows 10 environment 

### ISSUE THREAD

**Issue by Abocg** [Stable-X/StableDelight#4]
Hi. Thanks for the amazing work. Am trying to run it on windows environment python 3.10 but i couldn't. Am getting this error.... Collecting nvidia-nccl-cu12 
  Downloading nvidia-nccl-cu12-0.0.1.dev5.tar.gz (4.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ASUS\AppData\Local\Temp\pip-install-171h8_m9\nvidia-nccl-cu12_d1f65921487e4e7293ebf23597e56b56\setup.py", line 152, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      
      $ pip install nvidia-pyindex
      $ pip install nvidia-nccl-cu12
      
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Location 'pip/' is ignored: it is either a non-existing path or lacks a specific scheme.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Zerui-Yu** [comment]
This is because some packages in the environment.txt only belongs to Linux, not the Windows. I also had these problems you mentioned in Windows 10, after that I tried to create the environment in WSL2 and it worked.
